### ISSUE TITLE
Inconsistent with PowerShellPracticeAndStyle

### ISSUE THREAD

**Issue by OCram85** [nicholasdille/professional-powershell#31]
Hi Nicholas,

I often recommend respecting the [PowerShellPracticeAndStyle](https://github.com/PoshCode/PowerShellPracticeAndStyle) which is the most known best practice for PowerShell.

While watching your presentation I was thinking about the following things:

- Capitalization
  - I think you mean PascalCase?
- Maximum line length
  - 70 seems a bit to short. If you work with nested constructs and each one is indented by 4 spaces you won't have much space ^^ - Even if you use splatting.
-  Avoid backticks
   - Backticks are really hard to see. If you use an editor with dark color themes you really have a hard time. You could loose a lot of time while debugging scripts with backtick at the end of a line. 

Maye there are some topics you could align with the mentioned best practice :smile:

**Comment by nicholasdille** [comment]
Very valid points. I must admit I have not thought of referring to the PowerShellPracticeAndStyle. My bad. It makes sense to align with those guidelines!

**Comment by ChrisLGardner** [comment]
Also on the subject of backticks for line endings, you show an example which has a backtick and then a pipe on the next line but you can line break at a pipe and it will happily continue working without needing a backtick.

```
Get-ChildItem -Path C:\Some\Path\Over\Here -Recurse |
    Select-Object -First 5 -ExpandProperty FullName
```

**Comment by nicholasdille** [comment]
I will refactor the chapters about formatting, line breaks and abbreviations by linking to [PowerShellPracticeAndStyle](https://github.com/PoshCode/PowerShellPracticeAndStyle). I will track the changes in this issue

**Comment by nicholasdille** [comment]
Considering the latest comments, removing style recommendation in favour of linking to existing work seems to be the right thing todo!
